[params]
  promoHeadline = "30 Jahre freie Energie aus der Sonne für Dich"
  promoSubline   = "Wir bieten hochklassige Produkte und lange Garantien"
  headline       = "OWN THE SUN"
  subheadline    = "Erlebe die Kraft der Sonne in deinem Zuhause. Nachhaltige Energie für eine strahlende Zukunft."
  ctaText        = "Jetzt anfragen"
  ctaLink        = "/kontakt"
